### ISSUE TITLE
Cheat Mode

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [SifVerT/SifDocs#1]
What do you mean by:

`Make sure that you have toggled on 'Cheat Mode' in the Mod Config page (main menu).`

I can't finde a toggle like that.

**Comment by SifVerT** [comment]
Could be renamed after I wrote the docs. It's the terrain delete feature you're looking for? I did at first think of it as a cheat but changed my mind.

**Comment by mariomurrent-softwaresolutions** [comment]
Ah I see. Is it working for you in the current version?

I can't delete Terrain although I have enabled this feature.

**Comment by mariomurrent-softwaresolutions** [comment]
Ah I see. Is it working for you in the current version?

I can't delete Terrain although I have enabled this feature.

**Comment by SifVerT** [comment]
Do you hold the modifier key as explained (default shift)?

**Comment by mariomurrent-softwaresolutions** [comment]
Yea, did not work 🙁 did everything as it is on the docs

**Comment by SifVerT** [comment]
And are you in the build gun's dismantle mode?

**Comment by mariomurrent-softwaresolutions** [comment]
Yes

**Comment by SifVerT** [comment]
And what are you trying to remove? Can you please record a video clip and upload to my support Discord? I haven't seen any problems with starting the dismantle script, that it doesn't even say it's removing something. Show your config page also if you can.

**Comment by mariomurrent-softwaresolutions** [comment]
Seems to work now
